# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sim_SP <- function(x_, cstar_, model_, corrFn_, keepPsi_, covPar_, alpha_) {
    .Call('_MSP_Sim_SP', PACKAGE = 'MSP', x_, cstar_, model_, corrFn_, keepPsi_, covPar_, alpha_)
}

Sim_Reich <- function(x_, knots_, Sigma_, keepPsi_, bw_, alpha_) {
    .Call('_MSP_Sim_Reich', PACKAGE = 'MSP', x_, knots_, Sigma_, keepPsi_, bw_, alpha_)
}

Sim_Smith <- function(x_, cstar_, keepPsi_, Sigma_, radius_) {
    .Call('_MSP_Sim_Smith', PACKAGE = 'MSP', x_, cstar_, keepPsi_, Sigma_, radius_)
}

